version: "3.8"

services:
  db:
    image: postgres:15
    container_name: amora_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amora_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/amora
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./amora-simulator-frontend
    container_name: amora_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./amora-simulator-frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
  backend_logs:
